# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webapp1:
    image: webapp1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5283:5283
